name: Build and Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build with Docker
        run: bash build-with-docker.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-core-dist
          path: wasm/packages/core/dist/**

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-core-dist
          path: dist

      - name: GH Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          files: dist/**
