name: Build, release, and publish
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build with Docker
        run: bash build-with-docker.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-core-dist
          path: wasm/packages/core/**

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-core-dist
          path: core

      - name: GH Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          files: core/dist/**
          tag_name: ${{ inputs.tag }}

  publish:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-core-dist
          path: core

      - run: npm publish --provenance --access public
        working-directory: ./core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
